[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "intellirity"
version = "0.1.0"
description = "Intellirity AI security SDK"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["requests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["intellirity*"]
